name: alpha-factor-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyter
  - boto3
  - botocore
  - python-dotenv
  - pandas
  - tqdm
  - matplotlib
  - numpy
  - sqlalchemy
  - jupyterlab
  - notebook
  - pip
  - pip:
      - polygon-api-client
      - alphalens-reloaded
      - vectorbt
